### ISSUE TITLE
Newbie  doubt  about frestq protocol

### ISSUE THREAD

**Issue by jsperezg** [agoravoting/frestq#28]
This is not an issue but a doubt. I'm tryint to deploy an Agora server, which internally uses frestq. The frestq server is running on port 5000 with an self signed  certificate. At this moment I'm getting the following errors:

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): aut1.aspgems.com
DEBUG:root:RECEIVED MESSAGE in queue launch_task
Traceback (most recent call last):
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/frestq/api.py", line 101, in post_message
    if certs_differ(sender_ssl_cert, local_ssl_cert):
  File "/home/eorchestra/venv/local/lib/python2.7/site-packages/frestq/protocol.py", line 44, in certs_differ
    raise SecurityException()
frestq.protocol.SecurityException
```
I don't what do I need to check  nor look at in order to fix this issue. Could you please give me some clue or advice about what might be happening?

**Comment by jsperezg** [comment]
I forgot to say that it's running on top of Ubuntu  14.04
